openapi: 3.0.0
info:
  title: eMPF API Specification - Contribution Module
  description: eMPF API Specification - Contribution Module
  version: 0.1.0
paths:
  /cas/ad/contribution/external/v1/bill/list:
    get:
      tags:
        - ER-Portal-API
      summary: CON-PERIOD-BILLABLE CON - Retrieve period bill
      description: |
        **API ID:** CON-PERIOD-BILLABLE \
        **CM:** CM-Web-Employer-Contribution A1, A2, A3, A4, B1, B2, B3, B4 \
        **FS:** FS-UF-CON-REE-009,FS-UF-CON-CEE-001 \
        CON - Retrieve period bill
      parameters:
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          description: successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/periodBillableResponse'
        '400':
          $ref: '#/components/responses/400'
      security:
        - bearerAuth: []

components:
  parameters:
    pageSize:
      in: query
      required: true
      name: pageSize
      description: Page Size
      schema:
        enum:
          - 25
          - 50
          - 100
        example: 50
        type: integer
  schemas:
    GlobalSuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          description: The flag indicates there is no bussiness error occurred in the request
        code:
          type: integer
          example: '200'
    periodBillableResponse:
      allOf:
        - $ref: '#/components/schemas/GlobalSuccessResponse'
        - properties:
            payload:
              $ref: '#/components/schemas/periodBillablesResDto'
    periodBillablesResDto:
      type: object
      properties:
        pageRecords:
          type: integer
          example: 50
        page:
          type: integer
          example: 0
        pageSize:
          type: integer
          example: 50
        totalPages:
          type: integer
          example: 3
        totalRecords:
          type: integer
          example: 139
  responses:
    '400':
      description: Business validation exception

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
